config/routes.rb
ChiliProject::Application.routes.draw do
  devise_for :users
  resources :projects

  root 'projects#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Roar::Rails::ControllerAdditions

  before_action :set_representer_config

  # Copied from https://github.com/apotonick/roar-rails/pull/54
  def set_representer_config
    url_options = Rails.configuration.representer.default_url_options || {}
    url_options[:protocol] ||= request.protocol
    url_options[:host]     ||= request.host
    url_options[:port]     ||= request.port unless request.port == 80
    Rails.configuration.representer.default_url_options = url_options
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html
  represents :xml, Project
  represents :json, Project

  def new
    # form_for does some magic if we pass it an empty AR object as opposed
    # to just telling it we're working on a :project. That works for now, but
    # we probably don't want to keep this here.
    @project = Project.new
  end

  def create
    begin
      @project = project_creation_service.process(project_params)
      flash[:notice] = t('projects.creation_successful')
    rescue ProjectCreator::CreationError
      head status: :unprocessable_entity
      return
    end

    respond_with @project
  end

  def edit
    @project = Project.find(params[:id]).decorate
    respond_with @project
  end

  def update
    begin
      @project = project_update_service.process(params[:id], project_params)
      flash[:notice] = t('projects.update_successful')
    rescue ProjectUpdater::UpdateError
      head status: :unprocessable_entity
      return
    end

    respond_with @project
  end

  def show
    @project = Project.find(params[:id]).decorate
    respond_with @project
  end

  def index
    @projects = Project.all.decorate
    respond_with @projects
  end

  def destroy
    begin
      @project = project_destroy_service.process(params[:id])
      flash[:notice] = t('projects.destruction_successful')
    end

    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name) if params[:project].present?
  end

  def project_creation_service
    ProjectCreator.new
  end

  def project_update_service
    ProjectUpdater.new
  end

  def project_destroy_service
    ProjectDestroyer.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_flashes(*names)
    capture do
      names.each {|f| concat render_flash(f)}
    end
  end

  def render_flash(name)
    message = flash[name]
    return unless message.present?
    content_tag :div, class: name, :'data-alert' => true do
      concat message
      concat content_tag :a, '×', href: '#', class: :close
    end
  end
end

app/views/global/_global_menu.html.erb
<li><%= link_to 'Projects', projects_path -%></li>

app/views/global/_topbar_session.html.erb
<% if user_signed_in? -%>
  <li class="active has-dropdown">
    <a href="#"><%=t 'account.greeting', name: current_user.email -%></a>
    <ul class="dropdown">
      <li>
        <%= link_to t('account.my'), edit_user_registration_path -%>
        <%= link_to t('account.sign_out'), destroy_user_session_path, method: :delete %>
      </li>
    </ul>
  </li>
<% else -%>
  <li class="active">
    <%= link_to t('account.sign_in'), new_user_session_path %>
  </li>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>ChiliProject</title>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
      <h1><a href="/">ChiliProject</a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>
    <section class="top-bar-section">
      <ul class="right">
        <%= render 'global/topbar_session' %>
      </ul>

      <ul class="left">
        <%= render 'global/global_menu' -%>
      </ul>
    </section>
  </nav>


  <section role="main">
    <div class="row">
      <div class="medium-3 columns">
        <div class="sidebar">
        </div>
      </div>
      <div class="medium-9 columns">
        <%= render_flashes :alert, :notice -%>
        <%= yield %>
      </div>
    </div>
  </section>
  <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/projects/edit.html.erb
<div class="project <%= @project.html_class -%> edit">
  <h1><%=t 'projects.edit' -%></h1>
  <%= form_for @project do |f| %>
    <%= f.label :name, t('projects.attributes.name') -%>
    <%= f.text_field :name, placeholder: t('projects.singular_with_number', id: @project.id) %>
    <%= f.submit t('global.save'), class: :button %>
    <%# TODO: use a hidden back_link form parameter instead of rails magic -%>
    <%= link_to t('global.cancel'), :back, class: :button %>
  <% end %>
</div>

app/views/projects/index.html.erb
<h1><%=t 'projects.plural' -%></h1>
<ul class="projects">
  <% @projects.each do |project| -%>
    <li class="project"><%= project.named_link -%></li>
  <% end -%>
</ul>

app/views/projects/new.html.erb
<div class="project new">
  <h1><%=t 'projects.new' -%></h1>
  <%= form_for @project do |f| %>
    <%= f.label :name, t('projects.attributes.name') -%> <%= f.text_field :name %>
    <%= f.submit t('global.create'), class: :button %>
    <%# TODO: use a hidden back_link form parameter instead of rails magic -%>
    <%= link_to t('global.cancel'), :back, class: :button %>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="project <%= @project.html_class -%>">
  <h1><%= @project.name_or_default -%></h1>
  <%= link_to t('global.edit'), edit_project_path(@project) %>
  <%= link_to t('global.delete'), project_path(@project), method: :delete %>
</div>